#########################################################################
## Purpose: Makefile for Chap_1_Verification_Guidelines/homework_solution
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 14:57:35  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/03 22:06:50  Greg
## Updated to common Makefile and to use Makefile_non_DPI
##
#########################################################################

FILES = calc2_transaction.sv calc2_generator.sv   calc2_master.sv    calc2_interfaces.sv  calc2_monitor.sv  adder.v  alu_output_stage.v  holdreg.v  priority.v  top.sv  alu_input_stage.v  calc2_top.v  mux_out.v  shifter.v  calc2_scoreboard.sv  calc2_testcases.sv  SV_RAND_CHECK.sv  calc2_environment.sv  test_bench.sv calc2_coverage.sv



TOPLEVEL = top

include Makefiles/non_DPI/Makefile_non_DPI
